### ISSUE TITLE
'boundingRect' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by koenvanderdrift** [ChimeHQ/Glyph#3]
I added Glyph my project, and am getting these error messages for functions I am trying to access.

> 'boundingRect' is inaccessible due to 'internal' protection level

Should they be marked 'public'?

**Comment by mattmassicotte** [comment]
Arg, sorry about that! I've just make a bunch of changes here and I must have messed something up. Will have a look.

**Comment by mattmassicotte** [comment]
Ahh are you trying to use this on an `NSTextLayoutManager`? Can you go through the owning `NSTextContainer` instead?

**Comment by koenvanderdrift** [comment]
Yes, I am using (a subclass of) NSTextLayoutManager. I will have a look at NSTextContainer.

**Comment by mattmassicotte** [comment]
Ok I'm glad!

But I'm also not opposed to making this API public. It's slightly tricky, because the bounding areas of a single range can actually be, physically, not a rectangle (due to line fragments). But, it can still be useful, especially if you are looking for a single character/location.

I'm just going to make it public anyways with 8f7673b8eda4895ac69d5693cf1a122d3d4813bd

Also, please do not be shy about filing more issues. I'm actively working on this library, and I know it has a few holes. Plus the TextKit 2 stuff was extremely complex to get right, and I suspect some bugs are still lurking.

**Comment by koenvanderdrift** [comment]
I have been doing some more digging and found that I can get the rects of a text range using:

`
enumerateTextSegments(in: textRange, type: .standard, options: .rangeNotRequired) { _, rect, _, _ in

}
`

Link: https://developer.apple.com/documentation/appkit/nstextlayoutmanager/enumeratetextsegments(in:type:options:using:)

**Comment by mattmassicotte** [comment]
Ohhh how did I not notice that one before! Given the documentation I have to experiment a little with it but this looks awesome. Thanks for letting me know!

**Comment by mattmassicotte** [comment]
@koenvanderdrift just a quick warning - it appears that (at least on macOS 15) `enumerateTextSegments` only works correctly for the first line fragment of a line. I suspect this is due to the same thing that is causing me problems - the tricky behavior of `NSTextLineFragment.locationForCharacter(at:)`.

I'm fixing this in this library so `boundingRect` and other calculations that depend on this work right.
